# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7KVeyKoKVBVQI5dLalk9t2ZepFtOj_O

# **Task 1: Perform Basic Mathematical Operations**
"""



"""# Problem Statement: Write a Python program that does the following:
1.  Takes two numbers as input from the user.
2.  Performs the basic mathematical operations on these two numbers:
o	Addition
o	Subtraction
o	Multiplication
o	Division
3.  Displays the results of each operation on the screen.
"""

N1 = int(input("enter the number 1:"))
N2 = int(input("enter the number 2: "))

Addition = N1 + N2
subtraction = N1 - N2
Multiplication = N1 * N2
Division = N1/N2

print("Addition :",Addition)
print("subtraction :",subtraction)
print("Multiplication :",Multiplication)
print("Division :",Division)





"""## ***Task 2: Create a Personalized Greeting***"""



"""Problem Statement: Write a Python program that:
1.  Takes a user's first name and last name as input.
2.  Concatenates the first name and last name into a full name.
3.  Prints a personalized greeting message using the full name.
"""



Name1 = (input("Enter the first name: "))
Name = (input("Enter the last name: "))

cn = Name1 + " "+  Name + "!"
print("cn:",cn)

print("Hello", cn , "welcome to the python progra")













